### ISSUE TITLE
[Bug][Task Function is not working]

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#574]
Step1 : Go to Tasks tab
Because Map doesn't show, user can't perform any action 
Continue button is disable

**Comment by geohacker** [comment]
Thank you for the ticket @tailm1. This looks like the task process failed because of a few invalid geometries:

```
Processing line: 500Dumping districts
Processing line: 527undefined:1
{"type": "Feature", "geometry": {"type": "MultiPolygon", "coordinates": [[[[104.387008576, 22.679450306], [104.390612849, 22.6784423120001], [104.392374832, 22.678721403], [104.394430307, 22.6790698640001], [104.396413242, 22.6792135490001], [104.39780972, 22.6790826090001], [104.39854672, 22.6785404090001], [104.398643524, 22.6784487400001], [104.401017973, 22.6761994510001], [104.404560091, 22.672534148], [104.40737096, 22.6680486000001], [104.409555616, 22.663935415], [104.410446059, 22.6618269030001], [104.41067605, 22.659579759], [104.409806227, 22.6568516930001], [104.409076678, 22.6556909600001], [104.409007326, 22.6547370450001], [104.409788335, 22.6524578830001], [104.411855078, 22.6500811980001], [104.414365666, 22.6469568360001], [104.415552885, 22.6441001000001], [104.416115457, 22.6413432280001], [104.41730776, 22.6372602550001], [104.422368043, 22.630228023], [104.428043457, 22.625275566], [104.433768634, 22.621140541], [104.433888462, 22.6210539870001], [104.43625593, 22.619343938

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Stream.<anonymous> (/usr/lib/node_modules/geojson-stream-merge/index.js:32:29)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/usr/lib/node_modules/geojson-stream-merge/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/lib/node_modules/geojson-stream-merge/node_modules/through/index.js:45:5)
    at emit (/usr/lib/node_modules/geojson-stream-merge/node_modules/split/index.js:37:14)
    at Stream.<anonymous> (/usr/lib/node_modules/geojson-stream-merge/node_modules/split/index.js:60:7)
    at _end (/usr/lib/node_modules/geojson-stream-merge/node_modules/through/index.js:65:9)
    at Stream.stream.end (/usr/lib/node_modules/geojson-stream-merge/node_modules/through/index.js:74:5)
COPY 713
```

We will check further. 

cc @batpad

**Comment by geohacker** [comment]
I dug into this a bit more and it's not as bad as I thought. There are couple of things:

* This error comes from the fact that all the tasks in the queue refer to a way_id that is now deleted. So the API is sending empty geometry. We'll handle this in the API.
* The task process should handle this to remove these tasks that refer to ways that are currently visible=false. 

cc @batpad
